[workspace]
members = [
	"async_ui_core/",
	"async_ui_web/",
	"async_ui_web_html/",
	"async_ui_utils/",
	"async_ui_reactive/",
	"async_ui_gtk/",
	"async_ui_gtk_widgets",
	"examples/counters",
	"examples/gtk_counters",
	"examples/todomvc_gtk",
]