[package]
name = "async_ui_signals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pin-project-lite = "0.2.8"
async_ui_core = { path = "../async_ui_core/" }
futures = "0.3.21"
slab = "0.4.5"