[package]
name = "async_ui_web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scoped-tls = "1.0.0"
smol = "1.2.5"
pin-project-lite = "0.2.8"
sealed = "0.4"
async_ui_spawn = { path = "../async_ui_spawn/" }
smallvec = { version = "1.8.0", features = ["const_generics", "const_new", "union"] }

[dependencies.web-sys]
version = "0.3.56"
features = [
	'Node',
]